name: hogwarts_life_simulator
description: HogwartLige - 霍格沃茨AI人生模拟器
publish_to: 'none'
version: 3.3.5+335

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.33.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  provider: ^6.1.2
  shared_preferences: ^2.5.0
  uuid: ^4.3.3
  flutter_slidable: ^3.1.0
  path_provider: ^2.1.4
  flutter_secure_storage: ^9.0.0

dependency_overrides:
  win32: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatars/
